### ISSUE TITLE
Error loading extension: coc.nvim/lib/util not found

### ISSUE THREAD

**Issue by phcerdan** [neoclide/coc-snippets#11]
When entering neovim:

```
Error loading extension from /home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/index.js: Cannot find module 'coc.nvim/lib/util'
```

coc is installed with:
```
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': 'yarn install'}
```
And:
`:CocInstall coc-snippets`

CocInfo:
```
## versions

vim version: NVIM v0.3.4
node version: v11.10.0
coc.nvim version: 0.0.56
term: tmux-256color
platform: linux

## Error messages

```

**Comment by msmith-hpe** [comment]
I'm seeing the same thing here.

**Comment by iamcco** [comment]
same issue

**Comment by pgurung** [comment]
Same issue.
Log Message:
```2019-02-23T11:47:22.048 ERROR (pid:60912) [util-factoroy] - Error: Cannot find module 'coc.nvim/lib/util'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at req (/snapshot/coc.nvim/lib/util/factory.js:46:21)
    at Object.<anonymous> (/Users/<username>/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:14:16)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
```

**Comment by chemzqm** [comment]
Fixed, import issue.

**Comment by phcerdan** [comment]
Thanks @chemzqm, it is fixed now!
However facing a new issue, following on at #12
