### ISSUE TITLE
Uncaught exception in ultisnipsParser.js

### ISSUE THREAD

**Issue by phcerdan** [neoclide/coc-snippets#12]
```
[vim-node-coc]: Uncaught exception: Error: multiple line pattern not supported
    at Object.convertRegex (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/util.js:133:15)
    at body.replace (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/ultisnipsParser.js:64:40)
    at String.replace (<anonymous>)
    at Interface.rl.on.line (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/ultisnipsParser.js:63:29)
    at Interface.emit (events.js:197:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:449:12)
    at ReadStream.ondata (readline.js:165:10)
    at ReadStream.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
[vim-node-coc]: Uncaught exception: Error: multiple line pattern not supported
    at Object.convertRegex (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/util.js:133:15)
    at body.replace (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/ultisnipsParser.js:64:40)
    at String.replace (<anonymous>)
    at Interface.rl.on.line (/home/xxx/.config/coc/extensions/node_modules/coc-snippets/lib/ultisnipsParser.js:63:29)
    at Interface.emit (events.js:197:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:449:12)
    at ReadStream.ondata (readline.js:165:10)
    at ReadStream.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
```

**Comment by chemzqm** [comment]
I have no idea, since `\n` should not exists in regular expression.
