### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by garyxuehong** [neoclide/coc-snippets#16]
Hi after install I got the error as title.

there's more error in CocOpenLog

```
2019-03-08T14:01:35.208 ERROR (pid:66437) [util-factoroy] - TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/xueg/.config/coc/extensions/node_modules/coc-snippets/lib/list/snippet.js:12:39)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:58:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at req (/snapshot/coc.nvim/lib/util/factory.js:37:21)
    at Object.<anonymous> (/Users/xueg/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:9:43)
2019-03-08T14:01:43.137 ERROR (pid:67582) [util-factoroy] - TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/xueg/.config/coc/extensions/node_modules/coc-snippets/lib/list/snippet.js:12:39)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:58:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at req (/snapshot/coc.nvim/lib/util/factory.js:37:21)
    at Object.<anonymous> (/Users/xueg/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:9:43)

```

My node version is 10

**Comment by garyxuehong** [comment]
Got it work, just update the coc.nvim to latest version.
