### ISSUE TITLE
Error on TextChangedI: Cannot read property 'pre' of undefined

### ISSUE THREAD

**Issue by Menghongli** [neoclide/coc-snippets#189]
Got the following error in the new release
 ```
Error on TextChangedI: Cannot read property 'pre' of undefined
TypeError: Cannot read property 'pre' of undefined
    at /Users/menghongli/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:186:48
    at /Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:15365:55
    at new Promise (<anonymous>)
    at /Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:15360:24
    at /Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:15333:28
    at Array.map (<anonymous>)
    at Events.fire (/Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:15332:39)
    at NeovimClient.<anonymous> (/Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:10355:40)
    at NeovimClient.emit (events.js:310:20)
    at NeovimClient.emitNotification (/Users/menghongli/.config/nvim/plugged/coc.nvim/build/index.js:10662:18)
```

**Comment by chemzqm** [comment]
Update your coc.nvim

**Comment by Menghongli** [comment]
Thanks
