### ISSUE TITLE
Installation on ubuntu causes "Error on execute python script" in Neovim

### ISSUE THREAD

**Issue by newptcai** [neoclide/coc-snippets#214]
After installing coc-snippets, I get the follow error in Neovim. In vim I do not see this error.

```
[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invo
king 'python_execute_file' on channel 4:
error caught in request handler 'python_execute_file ('/tmp/nvimKawwyv/coc.nvim-65191/coc-ulti
snips-akIPJMCqBh.py', 1, 1)':
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/neovim/plugin/script_host.py", line 87, in python_exe
cute_file
    script = compile(f.read(), file_path, 'exec')
  File "/tmp/nvimKawwyv/coc.nvim-65191/coc-ultisnips-akIPJMCqBh.py", line 315
    output += f", ${placeholder_index}"
                                      ^
SyntaxError: invalid syntax
```

Neovim version
```
:version
NVIM v0.4.3                                                                           
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack
-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_L
OG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno
-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -W
implicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENER
ATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/
neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include
 -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim
-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by newptcai** [comment]
The problem vanished after remove and install coc-snippets again.

**Comment by skylite21** [comment]
Same error still exists for me even after reinstall.

**Comment by jrafaaael** [comment]
> Same error still exists for me even after reinstall.

same here

**Comment by chemzqm** [comment]
Checkout the generated python file which have name like: coc-ultisnips-akIPJMCqBh.py

**Comment by firstmover** [comment]
Python version is too low for the snippet. I created a [pull request](https://github.com/honza/vim-snippets/pull/1387)
