### ISSUE TITLE
Does coc-snippets require Python

### ISSUE THREAD

**Issue by dmshvetsov** [neoclide/coc-snippets#215]
I don't have python executable and when I'm installing coc-snippets I'm getting this error below

So my question does this extension require Python executable?

<img width="918" alt="Screen Shot 2021-03-28 at 4 41 36 PM" src="https://user-images.githubusercontent.com/3574904/112744583-fd7ced80-8fa9-11eb-9d9a-1f16d752b6f4.png">

## nvim version:

```
NVIM v0.5.0-dev+b79596e
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210328-82360-1ye21n6/build/config -I/tmp/neovim-20210328-82360-1ye21n6/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210328-82360-1ye21n6/build/src/nvim/auto -I/tmp/neovim-20210328-82360-1ye21n6/build/include
Compiled by d24v@Dmitrys-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-b79596e_2/share/nvim"
```

## coc info

```
## versions

vim version: NVIM v0.5.0-dev+b79596e
node version: v14.15.1
coc.nvim version: 0.0.80-d129f0f97e
coc.nvim directory: /Users/d24v/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-03-28T16:41:01.850 INFO (pid:18298) [plugin] - coc.nvim 0.0.80-d129f0f97e initialized with node: v14.15.1 after 176ms
2021-03-28T16:41:32.550 INFO (pid:18298) [attach] - receive notification: installExtensions [ 'coc-snippets' ]
2021-03-28T16:41:32.560 INFO (pid:18298) [model-installer] - Using npm from: /Users/d24v/.asdf/installs/nodejs/14.15.1/bin/npm
2021-03-28T16:41:32.562 INFO (pid:18298) [model-installer] - Get info from https://registry.npmjs.org/
2021-03-28T16:41:33.227 INFO (pid:18298) [model-installer] - Fetched info of coc-snippets {
  'dist.tarball': 'https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.4.1.tgz',
  'engines.coc': '^0.0.80',
  version: '2.4.1',
  name: 'coc-snippets'
}
2021-03-28T16:41:33.228 INFO (pid:18298) [model-installer] - Downloading from https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.4.1.tgz
2021-03-28T16:41:33.604 INFO (pid:18298) [model-installer] - Download progress 2.2%
2021-03-28T16:41:33.608 INFO (pid:18298) [model-installer] - Download progress 6.7%
2021-03-28T16:41:33.611 INFO (pid:18298) [model-installer] - Download progress 11.3%
2021-03-28T16:41:33.611 INFO (pid:18298) [model-installer] - Download progress 15.8%
2021-03-28T16:41:33.611 INFO (pid:18298) [model-installer] - Download progress 20.3%
2021-03-28T16:41:33.612 INFO (pid:18298) [model-installer] - Download progress 24.9%
2021-03-28T16:41:33.612 INFO (pid:18298) [model-installer] - Download progress 29.4%
2021-03-28T16:41:33.612 INFO (pid:18298) [model-installer] - Download progress 33.9%
2021-03-28T16:41:33.612 INFO (pid:18298) [model-installer] - Download progress 38.5%
2021-03-28T16:41:33.612 INFO (pid:18298) [model-installer] - Download progress 43.0%
2021-03-28T16:41:33.613 INFO (pid:18298) [model-installer] - Download progress 47.5%
2021-03-28T16:41:33.613 INFO (pid:18298) [model-installer] - Download progress 52.1%
2021-03-28T16:41:33.613 INFO (pid:18298) [model-installer] - Download progress 56.6%
2021-03-28T16:41:33.613 INFO (pid:18298) [model-installer] - Download progress 61.1%
2021-03-28T16:41:33.615 INFO (pid:18298) [model-installer] - Download progress 65.7%
2021-03-28T16:41:33.615 INFO (pid:18298) [model-installer] - Download progress 70.2%
2021-03-28T16:41:33.616 INFO (pid:18298) [model-installer] - Download progress 74.7%
2021-03-28T16:41:33.616 INFO (pid:18298) [model-installer] - Download progress 79.3%
2021-03-28T16:41:33.617 INFO (pid:18298) [model-installer] - Download progress 83.8%
2021-03-28T16:41:33.619 INFO (pid:18298) [model-installer] - Download progress 88.3%
2021-03-28T16:41:33.619 INFO (pid:18298) [model-installer] - Download progress 92.9%
2021-03-28T16:41:33.621 INFO (pid:18298) [model-installer] - Download progress 97.4%
2021-03-28T16:41:33.622 INFO (pid:18298) [model-installer] - Download progress 100.0%
2021-03-28T16:41:33.623 INFO (pid:18298) [model-download] - Download completed: https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.4.1.tgz
2021-03-28T16:41:33.624 INFO (pid:18298) [model-download] - Downloaded https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.4.1.tgz => /var/folders/md/v5bdtgms20xgm3xzk0whxrz40000gn/T/nvim88sTMN/coc-snippets-zPhpWL
2021-03-28T16:41:33.726 INFO (pid:18298) [model-installer] - Extension download at /var/folders/md/v5bdtgms20xgm3xzk0whxrz40000gn/T/nvim88sTMN/coc-snippets-zPhpWL
2021-03-28T16:41:33.731 INFO (pid:18298) [model-installer] - Update package.json at /Users/d24v/.config/coc/extensions/package.json
2021-03-28T16:41:33.731 INFO (pid:18298) [model-installer] - Installed extension coc-snippets@2.4.1 at /Users/d24v/.config/coc/extensions/node_modules/coc-snippets
2021-03-28T16:41:33.770 ERROR (pid:18298) [node-client] - request error on "nvim_command" [
  "exe 'py3file '.fnameescape('/var/folders/md/v5bdtgms20xgm3xzk0whxrz40000gn/T/nvim88sTMN/coc.nvim-18298/coc-ultisnips-wjgxuRw7Mb.py')"
] Vim(py3file):E319: No "python3" provider found. Run ":checkhealth provider" Error
    at tM.request (/Users/d24v/.config/nvim/plugged/coc.nvim/build/index.js:20:34604)
    at tM.command (/Users/d24v/.config/nvim/plugged/coc.nvim/build/index.js:22:6887)
    at UltiSnippetsProvider.executePythonCode (/Users/d24v/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2511:40)
    at UltiSnippetsProvider.init (/Users/d24v/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2202:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async ProviderManager.init (/Users/d24v/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:462:5)
2021-03-28T16:43:36.307 INFO (pid:18298) [language-client-index] - eslint started with 22589
2021-03-28T16:45:44.549 INFO (pid:18298) [attach] - receive notification: showInfo []
```

## coc settings

```
{
  "coc.preferences.formatOnSaveFiletypes": ["typescript", "typescriptreact"],
  "tsserver.enableJavascript": false,
  "coc.source.buffer.enable": true,
  "snippets.ultisnips.usePythonx": false
}
```

**Comment by chemzqm** [comment]
It's requries your vim support python.
