### ISSUE TITLE
import_coc5.workspace.languageIds is not iterable

### ISSUE THREAD

**Issue by dadav** [neoclide/coc-snippets#272]
Just updated my plugins and now I'm getting this error all the time:

```bash
2022-03-13T18:53:27.973 ERROR (pid:44241) [node-client] - import_coc5.workspace.languageIds is not iterable TypeError: import_coc5.workspace.languageIds is not iterable        at TextmateProvider.init ($HOME/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2706:50)                                                         
      at processTicksAndRejections (node:internal/process/task_queues:94:5)                                                                                                 
      at async Promise.all (index 1)                                                                                                                                        
      at async ProviderManager.init ($HOME/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:1373:5)     
```

My setup:
```bash
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
```

**Comment by chemzqm** [comment]
You need upgrade coc.nvim to latest version as well.
