### ISSUE TITLE
global python code in .vim/pythonx

### ISSUE THREAD

**Issue by xilefsensei** [neoclide/coc-snippets#299]
UltiSnips supports putting python files into `~/.vim/pythonx`. This makes it possible to share python-code between snippets for different filetypes.
This generally also works with coc-snippets, but apparently it is not possible to use the `snip` object in that code. When I have a python-function in `/.vim/pythonx` that accesses, e.g., `snip.buffer`, I get the error

`NameError: name 'snip' is not defined`

Am I doing something wrong? Or is this a bug, or intended behaviour?
I have multiple big python-functions that I use for snippets for different filetypes, so this feature would be really nice for me to avoid duplicate code.

**Comment by chemzqm** [comment]
Need an example python file.

**Comment by xilefsensei** [comment]
`~/.vim/pythonx/ex.py`:
```python
def funca(): # works
    return 'success'

def funcb(): # does not work
    return snip.fn
```

And then, for example, `markdown.snippets`:
```snippets
global !p
from ex import *  # provides "funca" and "funcb"
endglobal

snippet testgood "example"
this works: `!p snip.rv = funca()`
this also works: `!p snip.rv = snip.fn`
endsnippet

snippet testbad "example"
this doesnt work: `!p snip.rv = funcb()`
endsnippet
```

Then open, for example, `a.md`. Using the snippets `testgood` will work, but `testbad` will expand to nothing. It also produces no error message in `:CocCommand snippets.openOutput`. (My original problem was slightly different, but with an older version of coc-snippets. I slightly changed the example, because this is simpler.)

**Comment by chemzqm** [comment]
Same error with latest ultisnips
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 47, in wrapper
    return func(self, *args, **kwds)
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 178, in expand
    if not self._try_expand():
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 818, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 767, in _do_snippet
    snippet_instance = snippet.launch(
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 534, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 102, in update_textobjects
    if obj._update(done, buf):
  File "/Users/chemzqm/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 285, in _update
    exec(compiled_code, self._locals)  # pylint:disable=exec-used
  File "<exec-interpolation-code>", line 1, in <module>
  File "/Users/chemzqm/.config/nvim/pythonx/ex.py", line 3, in funca
    return snip.fn
NameError: name 'snip' is not defined

Executed snippet code:
  1   snip.rv = funca()

```
